# Dataset config
data:
  root: '/kaggle/input/hr-lr-sar'
  train_batch_size: 6
  test_batch_size: 6
  num_workers: 2

# Training config
train:
  epochs: 50
  lr: 0.000001


# Model architecture config
model:
  num_ifs: 3

  pfe:
    in_channels: 1
    out_channels: 72
  
  hfe:
    in_c: 72
    out_c: 72
    kernel_size: 6
    padding: 2
    stride: 2
    num_blocks: 4
  
  rec:
    in_c: 72
    out_c: 1

  ifs:
    in_c: 72
    out_c: 72
    num_groups: 3
    kernel_size: 6
    padding: 2
    stride: 2